account/urls.py
from account.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'auth'

urlpatterns = [
    path('login/', userLogin, name="login"),
    path('logout/', userLogout, name='logout'),
    path('register/', userRegister, name="register"),

    path('forget-password/', password_reset_request, name="forgetPassword"),
    path('forget-password/confirm/', password_reset_confirm, name="forgetPasswordConfirm"),

    path('profile/', userProfile, name="profile"),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from base.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('change-language/<str:lang_code>/', change_language, name='change_language'),

    path('', home, name="home"),
    path('about', about, name="about"),
    path('services', services, name="services"),
    path('contact', contact, name="contact"),
    
    path('jobs/', getJobs, name="getJobs"),
    path('job/<slug>/', showJobDetails, name="showJobDetails"),

    path('nannies/', getNannies, name="getNannies"),
    path('nanny/<slug>/', showNanny, name="showNanny"),

    path('dashboard/', dashboard, name="dashboard"),

    # Client
    path('client/job-listings/', getJobListings, name="getJobListings"),
    path('client/job-listing/add/', addJobListing, name="addJobListing"),
    path('client/job-listing/edit/<slug:slug>/', editJobListing, name="editJobListing"),
    path('client/job-listing/delete/<slug:slug>/', deleteJobListing, name="deleteJobListing"),

    path('client/applicants/', getJobApplicants, name="getJobApplicants"),
    path('client/applicant/<id>/', getJobApplicantDetails, name="getJobApplicantDetails"),
    path('client/applicant/accept/<int:id>/', acceptApplication, name='acceptApplication'),
    path('client/applicant/reject/<int:id>/', rejectApplication, name='rejectApplication'),

    path('client/hire-applications/', getHireApplications, name="getHireApplications"),
    path('client/hire-applications/<id>/', getHireApplicationDetails, name="getHireApplicationDetails"),

    # Nanny
    path('job-applications/', getJobApplications, name="getJobApplications"),
    path('job-application/<id>/', getJobApplicationDetails, name="getJobApplicationDetails"),

    path('hire-applications/', getNannyHireApplications, name="getNannyHireApplications"),
    path('hire-applications/<id>/', getNannyHireApplicationDetails, name="getNannyHireApplicationDetails"),
    path('hire-application/accept/<int:id>/', nannyAcceptHireApplication, name='nannyAcceptHireApplication'),
    path('hire-application/reject/<int:id>/', nannyRejectHireApplication, name='nannyRejectHireApplication'),

    # path('profile/', updateProfile, name='updateProfile'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kna/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('', include('base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/nannies/index.html
{% extends 'layouts/app.html' %}
{% load humanize %}
{% block content %}

    <section class="box-section background-body py-96 border-bottom">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-md-8">
                    <h4 class="neutral-1000">
                        Nos Nounous
                    </h3>
                    <p class="text-md-medium neutral-500">
                        Familles et institutions ayant besoins d'une nounou ou une assistante maternelle ou un travailleur domestique.
                    </p>
                </div>
                <div class="col-md-4">
                    <div class="d-flex justify-content-end mt-md-0 mt-4">
                        <a class="btn btn-primary rounded-3" href="{% url 'auth:register' %}">
                            Become a nanny
                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M8 15L15 8L8 1M15 8L1 8" stroke="" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row mt-60">
                {% for nanny in nannies %}
                    <div class="col-lg-4 col-sm-6">
                        <div class="card-contact card-dealer d-flex">
                            <div class="card-image me-3">
                                <div class="position-relative">
                                    {% if nanny.image %}
                                            <img src="{{ nanny.image.url }}" alt="{{ job.title }}"  style="width: 60px; border-radius: 50%;" />
                                    {% else %}
                                        <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" style="width: 60px; border-radius: 50%;" alt="{{ job.title }}" />
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-info">
                                <div class="card-title">
                                    <a class="title heading-6" href="{% url 'base:showNanny' nanny.slug %}">
                                        {{ nanny.name }}
                                    </a>
                                    <p class="text-md-medium neutral-500">
                                        Phone Number <strong>{{ nanny.phone_number }}</strong>
                                    </p>
                                </div>
                                <div class="card-method-contact2">
                                    <a class="btn btn-primary" href="{% url 'base:showNanny' nanny.slug %}">
                                        Hire Me
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">
                                <svg width="12" height="12" viewbox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M6.00016 1.33325L1.3335 5.99992M1.3335 5.99992L6.00016 10.6666M1.3335 5.99992H10.6668" stroke="" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>
                            </span>
                        </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link active" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">4</a></li>
                    <li class="page-item"><a class="page-link" href="#">5</a></li>
                    <li class="page-item"><a class="page-link" href="#">...</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">
                                <svg width="12" height="12" viewbox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.99967 10.6666L10.6663 5.99992L5.99968 1.33325M10.6663 5.99992L1.33301 5.99992" stroke="" stroke-linecap="round" stroke-linejoin="round"></path>
                                </svg>
                            </span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>

{% endblock content %}

templates/pages/nannies/show.html
{% extends 'layouts/app.html' %}
{% load humanize %}
{% block content %}

<div class="page-header pt-30 background-body">
    <div class="custom-container position-relative mx-auto">
        <div class="bg-overlay rounded-12 overflow-hidden">
            <img class="w-100 h-100 img-banner" src="https://upload.wikimedia.org/wikipedia/commons/7/78/KCC_Wallpaper_by_Mudahunga.jpg" alt="Carento" />
        </div>
        <div class="container position-absolute z-1 top-50 start-50 translate-middle">
            <h2 class="text-white">
                {{ nanny.name }}
            </h2>
            <span class="text-white text-xl-medium">Since {{ nanny.created_at|date }}</span>
        </div>
    </div>
</div>

<section class="box-section box-content-tour-detail box-content-room-detail background-body border-bottom">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="box-collapse-expand">
                    <div class="group-collapse-expand">
                        <button class="btn btn-collapse" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOverview" aria-expanded="false" aria-controls="collapseOverview">
                            <h6>Overview</h6>
                            <svg width="12" height="7" viewbox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M1 1L6 6L11 1" stroke="" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            </svg>
                        </button>
                        <div class="collapse show" id="collapseOverview">
                            <div class="card-contact border-0 border-bottom rounded-0 d-flex">
                                <div class="card-image me-3">
                                    <div class="position-relative">
                                        <img src="https://static.vecteezy.com/system/resources/thumbnails/005/129/844/small_2x/profile-user-icon-isolated-on-white-background-eps10-free-vector.jpg" alt="Carento" style="width: 100px; height: 100px;" />
                                    </div>
                                </div>
                                <div class="card-info">
                                    <div class="card-title">
                                        <a class="title heading-6" href="#">{{ nanny.name }}</a>
                                        <p class="text-md-medium neutral-500">
                                            Location here
                                        </p>
                                    </div>
                                    <div class="card-method-contact2">
                                        <a class="email text-xs-bold" href="#">
                                            Open to work
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="card card-body">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="sidebar-left border-1 background-card">
                    <h6 class="text-xl-bold neutral-1000">Get in touch</h6>
                    <div class="box-sidebar-content">
                        {% if login_required %}
                            <!-- If user is not logged in, show login prompt -->
                            <div class="alert alert-warning">
                                Please <a href="{% url 'auth:login' %}">log in</a> to apply for this job.
                            </div>
                        {% elif client_required %}
                            <!-- If user has a role other than 'Client' -->
                            <div class="alert alert-warning">
                                You need to <a href="{% url 'auth:logout' %}">register as a client</a> to hire a nanny.
                            </div>
                        {% else %}
                            <!-- If the user is a client and hasn't applied yet -->
                            {% if already_applied %}
                                <div class="alert alert-info">
                                    You have already sent a hire application to this nanny.
                                </div>
                            {% else %}
                                <form class="form-contact" method="POST">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                {{ form.job_title }}
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                {{ form.expected_salary }}
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                {{ form.expected_start_date }}
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                {{ form.expected_end_date }}
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                {{ form.work_schedule }}
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                {{ form.description }}
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <button class="btn btn-book">
                                                Send message
                                                <svg width="17" height="16" viewbox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M8.5 15L15.5 8L8.5 1M15.5 8L1.5 8" stroke="" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}