base/urls.py
from base.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('change-language/<str:lang_code>/', change_language, name='change_language'),

    path('', home, name="home"),
    path('about', about, name="about"),
    path('services', services, name="services"),
    path('contact', contact, name="contact"),
    
    path('jobs/', getJobs, name="getJobs"),
    path('job/<slug>/', showJobDetails, name="showJobDetails"),

    path('nannies/', getNannies, name="getNannies"),
    path('nanny/<slug>/', showNanny, name="showNanny"),

    path('dashboard/', dashboard, name="dashboard"),

    # Client
    path('client/job-listings/', getJobListings, name="getJobListings"),
    path('client/job-listing/add/', addJobListing, name="addJobListing"),
    path('client/job-listing/edit/<slug:slug>/', editJobListing, name="editJobListing"),
    path('client/job-listing/delete/<slug:slug>/', deleteJobListing, name="deleteJobListing"),

    path('client/applicants/', getJobApplicants, name="getJobApplicants"),
    path('client/applicant/<id>/', getJobApplicantDetails, name="getJobApplicantDetails"),
    path('client/applicant/accept/<int:id>/', acceptApplication, name='acceptApplication'),
    path('client/applicant/reject/<int:id>/', rejectApplication, name='rejectApplication'),

    path('client/hire-applications/', getHireApplications, name="getHireApplications"),
    path('client/hire-applications/<id>/', getHireApplicationDetails, name="getHireApplicationDetails"),

    # Nanny
    path('job-applications/', getJobApplications, name="getJobApplications"),
    path('job-application/<id>/', getJobApplicationDetails, name="getJobApplicationDetails"),

    path('hire-applications/', getNannyHireApplications, name="getNannyHireApplications"),
    path('hire-applications/<id>/', getNannyHireApplicationDetails, name="getNannyHireApplicationDetails"),
    path('hire-application/accept/<int:id>/', nannyAcceptHireApplication, name='nannyAcceptHireApplication'),
    path('hire-application/reject/<int:id>/', nannyRejectHireApplication, name='nannyRejectHireApplication'),

    # path('profile/', updateProfile, name='updateProfile'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kna/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('', include('base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/user/client/job-applicants/show.html
{% extends 'layouts/app.html' %}
{% load humanize %}
{% block content %}

<section class="box-section background-body pt-80">
    <div class="container">
        <div class="text-center">
            <div class="background-body px-3 py-2 rounded-12 border d-flex gap-3 d-inline-flex">
                <a href="{% url 'base:home' %}" class="neutral-700 text-md-medium">
                    {% if request.session.lang == 'en' %} Home {% else %} Accueil {% endif %}
                </a>
                <span>
                    <img src="https://carento-demo.vercel.app/assets/imgs/template/icons/arrow-right.svg" alt="Carento" />
                </span>
                <a href="{% url 'base:getJobApplicants' %}" class="neutral-1000 text-md-bold">
                    {% if request.session.lang == 'en' %} Applicants {% else %} Candidats {% endif %}
                </a>
                <span>
                    <img src="https://carento-demo.vercel.app/assets/imgs/template/icons/arrow-right.svg" alt="Carento" />
                </span>
                <a href="#" class="neutral-1000 text-md-bold">{{ applicant.job.title }}</a>
            </div>
            <h3 class="mt-3 neutral-1000">{{ applicant.job.title }}</h3>
        </div>
    </div>
</section>

<section class="box-section background-body pt-80 pb-110 dashboard">
    <div class="container">
        <div class="row">
            {% include 'inc/user-sidebar.html' %}

            <div class="col-xl-9 col-lg-8">
                <div class="row mb-3">
                    <div class="col-lg-3 mb-3 mb-lg-0">
                        <div class="card shadow-none flex-fill bg-1">
                            <div class="box-earning px-3 py-4 text-center">
                                <span class="avatar rounded-circle bg-primary me-3">
                                    <img src="https://static.vecteezy.com/system/resources/thumbnails/005/129/844/small_2x/profile-user-icon-isolated-on-white-background-eps10-free-vector.jpg" alt="image">
                                </span>
                                <p>{{ applicant.nanny.name }}</p>
                                <p>{{ applicant.nanny.phone_number }}</p>
                                <p>{{ applicant.nanny.email }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="card shadow-none flex-fill bg-3">
                            <div class="box-earning px-3 py-4">
                                <span class="neutral-1000 text-md-bold fs-5">
                                    {% if request.session.lang == 'en' %} Job Info {% else %} Infos sur l'emploi {% endif %}
                                </span>
                                <div class="row">
                                    <div class="col-lg-3">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Client Name {% else %} Nom du client {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.job.client.name }}</p>
                                    </div>
                                    <div class="col-lg-3">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Client Phone Number {% else %} Téléphone du client {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.job.client.phone_number }}</p>
                                    </div>
                                    <div class="col-lg-3">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Job {% else %} Emploi {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.job.title }}</p>
                                    </div>
                                    <div class="col-lg-2">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Job Salary {% else %} Salaire {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.job.salary|floatformat|intcomma }} RWF</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card shadow-none flex-fill bg-3">
                            <div class="box-earning px-3 py-4">
                                <span class="neutral-1000 text-md-bold fs-5">
                                    {% if request.session.lang == 'en' %} Application Info {% else %} Infos de candidature {% endif %}
                                </span>
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Experience {% else %} Expérience {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.experience }}</p>
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Availability {% else %} Disponibilité {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.availability|date }}</p>
                                    </div>
                                    <div class="col-lg-4">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Status {% else %} Statut {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">
                                            {% if applicant.status == 'accepted' %}
                                                <span class="badge badge-success rounded-pill d-inline-flex align-items-center fs-10">
                                                    <i class="fi fi-rr-check-circle me-1"></i> {% if request.session.lang == 'en' %} Accepted {% else %} Accepté {% endif %}
                                                </span>
                                            {% elif applicant.status == 'rejected' %}
                                                <span class="badge badge-danger rounded-pill d-inline-flex align-items-center fs-10">
                                                    <i class="fi fi-rr-door-closed me-1"></i> {% if request.session.lang == 'en' %} Rejected {% else %} Rejeté {% endif %}
                                                </span>
                                            {% elif applicant.status == 'pending' %}
                                                <span class="badge badge-warning rounded-pill d-inline-flex align-items-center fs-10">
                                                    <i class="fi fi-rr-hourglass me-1"></i> {% if request.session.lang == 'en' %} Pending {% else %} En attente {% endif %}
                                                </span>
                                            {% endif %}
                                        </p>
                                    </div>
                                    <div class="col-lg-12">
                                        <p class="fs-8 neutral-500 text-md-bold">
                                            {% if request.session.lang == 'en' %} Cover Letter {% else %} Lettre de motivation {% endif %}
                                        </p>
                                        <p class="fs-6 text-truncate">{{ applicant.cover_letter }}</p>
                                    </div>
                                </div>
                                {% if applicant.status == 'pending' %}
                                    <div class="d-flex gap-5 justify-content-between w-100 mt-4">
                                        <a href="{% url 'base:acceptApplication' application.id %}" class="text-primary-dark"
                                           onclick="confirmAction('{% if request.session.lang == 'en' %}Accept Application{% else %}Accepter la candidature{% endif %}', '{{ applicant.id }}', 'accept')">
                                            <i class="fi fi-rr-check"></i> {% if request.session.lang == 'en' %} Accept Application {% else %} Accepter la candidature {% endif %}
                                        </a>
                                        <a href="{% url 'base:rejectApplication' application.id %}" class="text-danger"
                                           onclick="confirmAction('{% if request.session.lang == 'en' %}Reject Application{% else %}Rejeter la candidature{% endif %}', '{{ applicant.id }}', 'reject')">
                                            <i class="fi fi-rr-do-not-enter"></i> {% if request.session.lang == 'en' %} Reject Application {% else %} Rejeter la candidature {% endif %}
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}