base/urls.py
from base.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('change-language/<str:lang_code>/', change_language, name='change_language'),

    path('', home, name="home"),
    path('about', about, name="about"),
    path('services', services, name="services"),
    path('contact', contact, name="contact"),
    
    path('jobs/', getJobs, name="getJobs"),
    path('job/<slug>/', showJobDetails, name="showJobDetails"),

    path('nannies/', getNannies, name="getNannies"),
    path('nanny/<slug>/', showNanny, name="showNanny"),

    path('dashboard/', dashboard, name="dashboard"),

    # Client
    path('client/job-listings/', getJobListings, name="getJobListings"),
    path('client/job-listing/add/', addJobListing, name="addJobListing"),
    path('client/job-listing/edit/<slug:slug>/', editJobListing, name="editJobListing"),
    path('client/job-listing/delete/<slug:slug>/', deleteJobListing, name="deleteJobListing"),

    path('client/applicants/', getJobApplicants, name="getJobApplicants"),
    path('client/applicant/<id>/', getJobApplicantDetails, name="getJobApplicantDetails"),
    path('client/applicant/accept/<int:id>/', acceptApplication, name='acceptApplication'),
    path('client/applicant/reject/<int:id>/', rejectApplication, name='rejectApplication'),

    path('client/hire-applications/', getHireApplications, name="getHireApplications"),
    path('client/hire-applications/<id>/', getHireApplicationDetails, name="getHireApplicationDetails"),

    # Nanny
    path('job-applications/', getJobApplications, name="getJobApplications"),
    path('job-application/<id>/', getJobApplicationDetails, name="getJobApplicationDetails"),

    path('hire-applications/', getNannyHireApplications, name="getNannyHireApplications"),
    path('hire-applications/<id>/', getNannyHireApplicationDetails, name="getNannyHireApplicationDetails"),
    path('hire-application/accept/<int:id>/', nannyAcceptHireApplication, name='nannyAcceptHireApplication'),
    path('hire-application/reject/<int:id>/', nannyRejectHireApplication, name='nannyRejectHireApplication'),

    # path('profile/', updateProfile, name='updateProfile'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kna/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('', include('base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
import os
import random
from account.models import *
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

class JobCategory(models.TextChoices):
    CHILD_CARE = 'child_care', _('Child Care')
    ELDERLY_CARE = 'elderly_care', _('Elderly Care')
    SICK_CARE = 'sick_care', _('Sick Care')
    DISABILITY_CARE = 'disability_care', _('Disability Care')
    HOUSEKEEPING = 'housekeeping', _('Housekeeping')
    PET_CARE = 'pet_care', _('Pet Care')
    NANNY_SHARE = 'nanny_share', _('Nanny Share')
    HOUSE_NANNY = 'house_nanny', _('House Nanny')
    LIVE_IN_NANNY = 'live_in_nanny', _('Live-in Nanny')
    NIGHT_NANNY = 'night_nanny', _('Night Nanny')
    SPECIAL_NEEDS_CARE = 'special_needs_care', _('Special Needs Care')
    SENIOR_CARE = 'senior_care', _('Senior Care')

class JobStatus(models.TextChoices):
    OPEN = 'open', _('Open')
    CLOSED = 'closed', _('Closed')
    PENDING = 'pending', _('Pending')
    IN_PROGRESS = 'in_progress', _('In Progress')

class JobPosting(models.Model):
    client = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='job_postings',
        limit_choices_to={'role': 'Client'}
    )
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.CharField(max_length=50, choices=JobCategory.choices)
    status = models.CharField(max_length=50, choices=JobStatus.choices, default=JobStatus.OPEN)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    location = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Generate slug based on the title and update it if the title changes
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)

    def generate_unique_slug(self):
        base_slug = slugify(self.title)
        slug = base_slug
        counter = 1
        while JobPosting.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        return slug

    def __str__(self):
        return f"{self.title} - {self.client.email}"

    class Meta:
        verbose_name = _('Job Posting')
        verbose_name_plural = _('Job Postings')

class ApplicationStatus(models.TextChoices):
    PENDING = 'pending', _('Pending')
    ACCEPTED = 'accepted', _('Accepted')
    REJECTED = 'rejected', _('Rejected')

class JobApplication(models.Model):
    nanny = models.ForeignKey(
        User, on_delete=models.CASCADE, limit_choices_to={'role': 'Nanny'}, related_name='applications'
    )
    job = models.ForeignKey(
        JobPosting, on_delete=models.CASCADE, related_name='applications'
    )
    experience = models.TextField(null=True, blank=True, help_text=_('Describe your experience relevant to this job.'))
    availability = models.DateField(null=True, blank=True, help_text=_('Specify your availability for the job.'))
    cover_letter = models.TextField(null=True, blank=True, help_text=_('Provide any additional information or comments.'))
    status = models.CharField(
        max_length=50, choices=ApplicationStatus.choices, default=ApplicationStatus.PENDING
    )
    applied_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Application for {self.job.title} by {self.nanny.name}"

    class Meta:
        verbose_name = _('Job Application')
        verbose_name_plural = _('Job Applications')
        unique_together = ('nanny', 'job')

class HireApplication(models.Model):
    client = models.ForeignKey(
        User, on_delete=models.CASCADE, limit_choices_to={'role': 'Client'}, related_name='hire_applications'
    )
    nanny = models.ForeignKey(
        User, on_delete=models.CASCADE, limit_choices_to={'role': 'Nanny'}, related_name='received_applications'
    )
    job_posting = models.ForeignKey(
        JobPosting, on_delete=models.SET_NULL, null=True, blank=True, related_name='hire_applications'
    )
    job_title = models.CharField(max_length=255, help_text='The title of the job the client is offering')
    description = models.TextField(help_text='Detailed description of the job')
    expected_start_date = models.DateField(help_text='Expected date for the nanny to start the job')
    expected_end_date = models.DateField(help_text='Expected date for the nanny to finish the job')
    expected_salary = models.DecimalField(max_digits=10, decimal_places=2, help_text='Expected salary for the nanny')
    work_schedule = models.TextField(help_text='Detailed work schedule for the nanny')
    additional_requirements = models.TextField(null=True, blank=True, help_text='Any additional requirements or comments from the client')
    status = models.CharField(
        max_length=50,
        choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
        default='pending',
        help_text='The current status of the application'
    )
    applied_at = models.DateTimeField(default=timezone.now, help_text='The time the nanny was applied to')
    updated_at = models.DateTimeField(auto_now=True, help_text='The time the application was last updated')

    def __str__(self):
        return f"Hire application from {self.client.name} to {self.nanny.name} for {self.job_title}"

    class Meta:
        verbose_name = 'Hire Application'
        verbose_name_plural = 'Hire Applications'
        unique_together = ('client', 'nanny', 'job_posting')

class NannyProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='nanny_profile')
    date_of_birth = models.DateField(null=True, blank=True)
    biography = models.TextField(null=True, blank=True, help_text=_('Brief biography of the nanny'))
    years_of_experience = models.PositiveIntegerField(null=True, blank=True)
    certifications = models.TextField(null=True, blank=True, help_text=_('Certifications or courses completed'))
    languages_spoken = models.TextField(null=True, blank=True, help_text=_('Languages spoken by the nanny'))
    previous_employers = models.TextField(null=True, blank=True, help_text=_('Details of previous employers'))
    hourly_rate = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, help_text=_('Hourly rate for services'))
    preferred_working_hours = models.TextField(null=True, blank=True, help_text=_('Preferred working hours'))
    availability_notes = models.TextField(null=True, blank=True, help_text=_('Any additional availability notes'))
    
    def __str__(self):
        return f"Nanny Profile for {self.user.name}"

    class Meta:
        verbose_name = 'Nanny Profile'
        verbose_name_plural = 'Nanny Profiles'

class ClientProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='client_profile')
    company_name = models.CharField(max_length=255, null=True, blank=True, help_text=_('Name of the company hiring the nanny'))
    company_description = models.TextField(null=True, blank=True, help_text=_('Brief description of the company'))
    address = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return f"Client Profile for {self.user.name}"

    class Meta:
        verbose_name = 'Client Profile'
        verbose_name_plural = 'Client Profiles'

def team_image_path(instance, filename):
    base_filename, file_extension = os.path.splitext(filename)
    timestamp = timezone.now().strftime("%Y%m%d%H%M%S")
    return f'team/member_{slugify(instance.name)}_{timestamp}.png'

class Team(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    position = models.CharField(max_length=255, null=True, blank=True)
    image = ProcessedImageField(
        upload_to=team_image_path,
        processors=[ResizeToFill(1333, 1694)],
        format='JPEG',
        options={'quality': 90},
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name if self.name else "Unnamed Team Member"
    
    class Meta:
        verbose_name_plural = "Team Members"

def logo_image_path(instance, filename):
    base_filename, file_extension = os.path.splitext(filename)
    timestamp = timezone.now().strftime("%Y%m%d%H%M%S")
    random_number = random.randint(1000, 9999)
    return f'settings/logo/{random_number}_{timestamp}{file_extension}'


class Setting(models.Model):
    logo = ProcessedImageField(
        upload_to=logo_image_path,
        # processors=[ResizeToFill(600, 600)],
        format='PNG',
        options={'quality': 90},
        null=True,
        blank=True
    )
    address = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    second_email = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    github = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def save(self, *args, **kwargs):
        # Ensure only one instance of settings can exist
        if not self.pk and Setting.objects.exists():

templates/pages/jobs/index.html
{% extends 'layouts/app.html' %}
{% load humanize %}
{% block content %}

    <section class="section-box pt-50 background-body">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-md-9 mb-30 wow fadeInUp">
                    <h4 class="title-svg neutral-1000 mb-15">
                        {% if request.session.lang == 'en' %} Latest Jobs {% else %} Offres d'emploi Récentes {% endif %}
                    </h4>
                    <p class="text-md-medium text-bold neutral-500">
                        {% if request.session.lang == 'en' %}
                            Find the latest job opportunities that match your skills.
                        {% else %}
                            Trouvez les dernières opportunités d'emploi correspondant à vos compétences.
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section class="box-section block-content-tourlist background-body">
        <div class="container">
            <div class="box-content-main pt-20">
                <div class="content-right">
                    <div class="box-filters mb-25 pb-5 border-bottom border-1">
                        <div class="row align-items-center">
                            <div class="col-xl-4 col-md-4 mb-10 text-lg-start text-center">
                                <div class="box-view-type">
                                    <span class="text-sm-bold neutral-500 number-found">
                                        {{ jobs_count }} 
                                        {% if request.session.lang == 'en' %} jobs found {% else %} emplois trouvés {% endif %}
                                    </span>
                                </div>
                            </div>
                            <div class="col-xl-8 col-md-8 mb-10 text-lg-end text-center">
                                <div class="box-item-sort">
                                    <form method="get" class="d-flex">
                                        <div class="item-sort border-1 me-3">
                                            <select name="limit" class="form-select" style="border: none;">
                                                <option value="12" {% if filter_params.limit == "12" %}selected{% endif %}>
                                                    {% if request.session.lang == 'en' %} Show: 12 {% else %} Afficher : 12 {% endif %}
                                                </option>
                                                <option value="30" {% if filter_params.limit == "30" %}selected{% endif %}>
                                                    {% if request.session.lang == 'en' %} Show: 30 {% else %} Afficher : 30 {% endif %}
                                                </option>
                                                <option value="50" {% if filter_params.limit == "50" %}selected{% endif %}>
                                                    {% if request.session.lang == 'en' %} Show: 50 {% else %} Afficher : 50 {% endif %}
                                                </option>
                                            </select>
                                        </div>
                                        <div class="item-sort border-1">
                                            <select name="sort" class="form-select" style="border: none;">
                                                <option value="newest" {% if filter_params.sort == "newest" %}selected{% endif %}>
                                                    {% if request.session.lang == 'en' %} Sort by (Newest) {% else %} Trier par (Plus récent) {% endif %}
                                                </option>
                                                <option value="oldest" {% if filter_params.sort == "oldest" %}selected{% endif %}>
                                                    {% if request.session.lang == 'en' %} Oldest {% else %} Plus ancien {% endif %}
                                                </option>
                                            </select>
                                        </div>
                                        <div class="card-button ms-2">
                                            <button type="submit" class="btn btn-gray" style="background: #70f46d;">
                                                {% if request.session.lang == 'en' %} Filter {% else %} Filtrer {% endif %}
                                            </button>
                                        </div>
                                        <div class="card-button">
                                            <a class="btn btn-gray" href="{% url 'base:getJobs' %}">
                                                {% if request.session.lang == 'en' %} Reset {% else %} Réinitialiser {% endif %}
                                            </a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-grid-tours wow fadeIn">
                        <div class="row">
                            {% for job in jobs %}
                                <div class="col-lg-4 col-md-6">
                                    <div class="card-journey-small background-card hover-up">
                                        <div class="pb-25"></div>
                                        <div class="card-info p-3 pt-30 border-top">
                                            <div class="card-title">
                                                <a class="text-lg-bold neutral-1000" href="{% url 'base:showJobDetails' job.slug %}">
                                                    {{ job.title|truncatechars:20 }}
                                                </a>
                                            </div>
                                            <div class="card-program">
                                                <ul class="list-style-disc ps-3 pe-4">
                                                    <li class="text-xs-medium neutral-1000">
                                                        {% if request.session.lang == 'en' %} Location {% else %} Lieu {% endif %} : <strong>{{ job.location }}</strong>
                                                    </li>
                                                    <li class="text-xs-medium neutral-1000">
                                                        {% if request.session.lang == 'en' %} Time {% else %} Temps {% endif %} : 
                                                        <strong>{{ job.start_date|date }} - {{ job.end_date|date }}</strong>
                                                    </li>
                                                    <li class="text-xs-medium neutral-1000">
                                                        {% if request.session.lang == 'en' %} Contact Number {% else %} Numéro de Contact {% endif %} : 
                                                        <strong>{{ job.client.phone_number }}</strong>
                                                    </li>
                                                    <li class="text-xs-medium neutral-1000">
                                                        {% if request.session.lang == 'en' %} Category {% else %} Catégorie {% endif %} : 
                                                        <strong>{{ job.get_category_display }}</strong>
                                                    </li>
                                                </ul>
                                                <div class="endtime pt-3 mt-3 border-top">
                                                    <a href="#" class="card-button pe-3">
                                                        {% if job.status == 'open' %}
                                                            <span class="badge badge-success rounded-pill d-inline-flex align-items-center fs-10">
                                                                <i class="fi fi-rr-check-circle me-1"></i> 
                                                                {% if request.session.lang == 'en' %} Open {% else %} Ouvert {% endif %}
                                                            </span>
                                                        {% elif job.status == 'closed' %}
                                                            <span class="badge badge-danger rounded-pill d-inline-flex align-items-center fs-10">
                                                                <i class="fi fi-rr-door-closed me-1"></i> 
                                                                {% if request.session.lang == 'en' %} Closed {% else %} Fermé {% endif %}
                                                            </span>
                                                        {% elif job.status == 'pending' %}
                                                            <span class="badge badge-warning rounded-pill d-inline-flex align-items-center fs-10">
                                                                <i class="fi fi-rr-hourglass me-1"></i> 
                                                                {% if request.session.lang == 'en' %} Pending {% else %} En attente {% endif %}
                                                            </span>
                                                        {% endif %}
                                                    </a>
                                                </div>
                                                <div class="endtime">
                                                    <div class="card-price">
                                                        <a href="{% url 'base:showJobDetails' job.slug %}" class="text-lg-bold neutral-1000" style="font-size: 16px;">
                                                            {{ job.salary|intcomma }} RWF / 
                                                            <span style="font-size: 12px;">
                                                                {% if request.session.lang == 'en' %} per day {% else %} par jour {% endif %}
                                                            </span>
                                                        </a>
                                                    </div>
                                                    <div class="card-button">
                                                        <a class="btn btn-gray" href="{% url 'base:showJobDetails' job.slug %}">
                                                            {% if request.session.lang == 'en' %} Apply {% else %} Postuler {% endif %}
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% include 'inc/job-sidebar.html' %}
            </div>
        </div>
    </section>

{% endblock content %}