account/urls.py
from account.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'auth'

urlpatterns = [
    path('login/', userLogin, name="login"),
    path('logout/', userLogout, name='logout'),
    path('register/', userRegister, name="register"),

    path('forget-password/', password_reset_request, name="forgetPassword"),
    path('forget-password/confirm/', password_reset_confirm, name="forgetPasswordConfirm"),

    path('profile/', userProfile, name="profile"),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from base.views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('change-language/<str:lang_code>/', change_language, name='change_language'),

    path('', home, name="home"),
    path('about', about, name="about"),
    path('services', services, name="services"),
    path('contact', contact, name="contact"),
    
    path('jobs/', getJobs, name="getJobs"),
    path('job/<slug>/', showJobDetails, name="showJobDetails"),

    path('nannies/', getNannies, name="getNannies"),
    path('nanny/<slug>/', showNanny, name="showNanny"),

    path('dashboard/', dashboard, name="dashboard"),

    # Client
    path('client/job-listings/', getJobListings, name="getJobListings"),
    path('client/job-listing/add/', addJobListing, name="addJobListing"),
    path('client/job-listing/edit/<slug:slug>/', editJobListing, name="editJobListing"),
    path('client/job-listing/delete/<slug:slug>/', deleteJobListing, name="deleteJobListing"),

    path('client/applicants/', getJobApplicants, name="getJobApplicants"),
    path('client/applicant/<id>/', getJobApplicantDetails, name="getJobApplicantDetails"),
    path('client/applicant/accept/<int:id>/', acceptApplication, name='acceptApplication'),
    path('client/applicant/reject/<int:id>/', rejectApplication, name='rejectApplication'),

    path('client/hire-applications/', getHireApplications, name="getHireApplications"),
    path('client/hire-applications/<id>/', getHireApplicationDetails, name="getHireApplicationDetails"),

    # Nanny
    path('job-applications/', getJobApplications, name="getJobApplications"),
    path('job-application/<id>/', getJobApplicationDetails, name="getJobApplicationDetails"),

    path('hire-applications/', getNannyHireApplications, name="getNannyHireApplications"),
    path('hire-applications/<id>/', getNannyHireApplicationDetails, name="getNannyHireApplicationDetails"),
    path('hire-application/accept/<int:id>/', nannyAcceptHireApplication, name='nannyAcceptHireApplication'),
    path('hire-application/reject/<int:id>/', nannyRejectHireApplication, name='nannyRejectHireApplication'),

    # path('profile/', updateProfile, name='updateProfile'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kna/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('account.urls')),
    path('', include('base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/footer.html
{% load static %}

<footer class="footer">
    <div class="container">
        <div class="footer-top">
            <div class="row align-items-center">
                <div class="col-lg-5 col-md-6 text-center text-md-start">
                    <h5 class="color-white wow fadeInDown">
                        {% if request.session.lang == 'en' %}
                            Subscribe to our newsletter
                        {% else %}
                            Abonnez-vous à notre newsletter
                        {% endif %}
                    </h5>
                </div>
                <div class="col-lg-7 col-md-6 text-center text-md-end mt-md-0 mt-4">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-end">
                        <form class="form-newsletter wow fadeInUp" action="#">
                            <input class="form-control" type="text" 
                                placeholder="{% if request.session.lang == 'en' %}Enter your email{% else %}Entrez votre e-mail{% endif %}"/>
                            <input class="btn btn-brand-2" type="submit" 
                                value="{% if request.session.lang == 'en' %}Subscribe{% else %}S'abonner{% endif %}"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-12 footer-1">
                <div class="mt-20 mb-20">
                    <a class="d-flex" href="{% url 'base:home' %}">
                        <img class="light-mode" alt="SAF" src="{{ settings.logo.url }}" style="width: 100px;"/>
                        <img class="dark-mode" alt="SAF" src="{{ settings.logo.url }}" style="width: 100px;"/>
                    </a>
                    <div class="box-info-contact mt-0">
                        <p class="text-md neutral-400 icon-address">
                            {% if request.session.lang == 'en' %}
                                Location
                            {% else %}
                                Emplacement
                            {% endif %}
                        </p>
                        <p class="text-md neutral-400 icon-email">
                            {{ settings.address }}
                        </p>
                    </div>
                    <div class="box-need-help">
                        <p class="need-help text-md-medium mb-5">
                            {% if request.session.lang == 'en' %}
                                Need help? Call us
                            {% else %}
                                Besoin d'aide ? Appelez-nous
                            {% endif %}
                        </p>
                        <br/>
                        <a class="heading-6 phone-support" href="#">
                            {{ settings.phone_number }}
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xs-6 footer-3">
                <h6 class="text-linear-3">
                    {% if request.session.lang == 'en' %}
                        About Us
                    {% else %}
                        À propos de nous
                    {% endif %}
                </h6>
                <ul class="menu-footer">
                    <li>
                        <a href="{% url 'base:services' %}" class="fw-bold">
                            {% if request.session.lang == 'en' %}
                                Our Services
                            {% else %}
                                Nos Services
                            {% endif %}
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-2 col-xs-6 footer-2">
                <h6 class="text-linear-3">
                    {% if request.session.lang == 'en' %}
                        What We Do
                    {% else %}
                        Ce que nous faisons
                    {% endif %}
                </h6>
                <ul class="menu-footer">
                    <li>
                        <a href="{% url 'base:getNannies' %}" class="fw-bold">
                            {% if request.session.lang == 'en' %}
                                Recommend nannies
                            {% else %}
                                Recommander des nounous
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'base:getNannies' %}" class="fw-bold">
                            {% if request.session.lang == 'en' %}
                                Nanny Training
                            {% else %}
                            Formation nounou
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'base:getNannies' %}" class="fw-bold">
                            {% if request.session.lang == 'en' %}
                                Nanny Placement and Coaching
                            {% else %}
                                Placement et coaching de nounou
                            {% endif %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom mt-50">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-6 text-md-start text-center mb-20">
                    <p class="text-sm color-white">
                        {% if request.session.lang == 'en' %}
                            © 2025 Comme chez Soi Burundi. All rights reserved. Developed by <a href='https://www.nexcodes.dev/' target='_blank' style="color: white;">NE<span style="color:red; font-weight: bold">X</span>CODE</a></p>
                        {% else %}
                            © 2025 Comme chez Soi Burundi. Tous droits réservés. Développé par <a href='https://www.nexcodes.dev/' target='_blank' style="color: white;">NE<span style="color:red; font-weight: bold">X</span>CODE</a></p>
                        {% endif %}
                    </p>
                </div>
                <div class="col-md-6 text-md-end text-center mb-20">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-end">
                        <p class="text-lg-bold neutral-0 d-inline-block mr-10">
                            {% if request.session.lang == 'en' %}
                                Follow us
                            {% else %}
                                Suivez-nous
                            {% endif %}
                        </p>
                        <div class="box-socials-footer d-inline-block">
                            <a class="icon-socials icon-instagram" href="#">
                                <!-- Instagram SVG Icon -->
                            </a>
                            <a class="icon-socials icon-facebook" href="#">
                                <!-- Facebook SVG Icon -->
                            </a>
                            <a class="icon-socials icon-twitter" href="#">
                                <!-- Twitter SVG Icon -->
                            </a>
                            <a class="icon-socials icon-be" href="#">
                                <!-- Another Social Icon -->
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/inc/job-sidebar.html
<div class="content-left order-lg-first">
    <div class="sidebar-left border-1 background-body">
        <div class="box-filters-sidebar">
            <div class="block-filter border-1">
                <h6 class="text-lg-bold item-collapse neutral-1000">
                    {% if request.session.lang == 'en' %}
                        Categories
                    {% else %}
                        Catégories
                    {% endif %}
                </h6>
                <div class="box-collapse scrollFilter">
                    <ul class="list-filter-checkbox">
                        {% for code, name in job_categories %}
                            <li>
                                <a href="#" class="text-sm-medium">
                                    {{ name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar-left border-1 background-body">
        <div class="box-filters-sidebar">
            <div class="block-filter border-1">
                <h6 class="text-lg-bold item-collapse neutral-1000">
                    {% if request.session.lang == 'en' %}
                        Job Status
                    {% else %}
                        Statut du poste
                    {% endif %}
                </h6>
                <div class="box-collapse scrollFilter">
                    <ul class="list-filter-checkbox">
                        {% for status_code, status_name in job_statuses %}
                            <li>
                                <a href="#" class="text-sm-medium">
                                    {{ status_name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/inc/user-sidebar.html
<div class="col-xl-3 col-lg-4">
    <div class="card user-sidebar mb-4">
        <div class="card-header user-sidebar-header">
            <div class="profile-content rounded-pill">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center justify-content-center py-2">
                        <img src="https://static.vecteezy.com/system/resources/thumbnails/005/129/844/small_2x/profile-user-icon-isolated-on-white-background-eps10-free-vector.jpg" 
                            alt="image" class="img-fluid avatar avatar-lg rounded-circle me-3">
                        <div>
                            <p class="fw-bold fs-5">{{ request.user.name }} ({{ request.user.role }})</p>
                            <span class="fs-14 text-gray-6">
                                {% if request.session.lang == 'en' %}
                                    Since {{ request.user.created_at|date }}
                                {% else %}
                                    Depuis {{ request.user.created_at|date }}
                                {% endif %}
                            </span>
                        </div>
                    </div>
                    <div>
                        <div class="d-flex align-items-center justify-content-center">
                            <a href="{% url 'auth:profile' %}" class="p-1 rounded-circle align-items-center justify-content-center btn-edit">
                                <i class="fi fi-rr-pencil fs-7"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body user-sidebar-body">
            <ul class="dashboard-sidebar-menu">
                {% if user.role == 'Client' %}
                    <li class="py-2">
                        <a href="{% url 'base:dashboard' %}">
                            <i class="fi fi-rr-dashboard"></i>
                            {% if request.session.lang == 'en' %}
                                Dashboard
                            {% else %}
                                Tableau de bord
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getJobListings' %}">
                            <i class="fi fi-rr-briefcase me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                Job Listing
                            {% else %}
                                Offres d'emploi
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getJobApplicants' %}">
                            <i class="fi fi-rr-users-alt me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                Applicants
                            {% else %}
                                Candidats
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getHireApplications' %}">
                            <i class="fi fi-rr-calendar me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                Hire Applications
                            {% else %}
                                Demandes d'embauche
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'auth:profile' %}">
                            <i class="fi fi-rr-user-md me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                My Profile
                            {% else %}
                                Mon profil
                            {% endif %}
                        </a>
                    </li>
                {% elif user.role == 'Nanny' %}
                    <li class="py-2">
                        <a href="{% url 'base:dashboard' %}">
                            <i class="fi fi-rr-dashboard"></i>
                            {% if request.session.lang == 'en' %}
                                Dashboard
                            {% else %}
                                Tableau de bord
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getJobApplications' %}">
                            <i class="fi fi-rr-Booking me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                My Applicants
                            {% else %}
                                Mes candidatures
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'base:getNannyHireApplications' %}">
                            <i class="fi fi-rr-calendar me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                Hire Applications
                            {% else %}
                                Demandes d'embauche
                            {% endif %}
                        </a>
                    </li>
                    <li class="py-2">
                        <a href="{% url 'auth:profile' %}">
                            <i class="fi fi-rr-user-md me-1"></i> 
                            {% if request.session.lang == 'en' %}
                                My Profile
                            {% else %}
                                Mon profil
                            {% endif %}
                        </a>
                    </li>
                {% else %}
                    <li class="py-2">
                        <p>
                            {% if request.session.lang == 'en' %}
                                You are not authorized to view navigation links.
                            {% else %}
                                Vous n'êtes pas autorisé à voir les liens de navigation.
                            {% endif %}
                        </p>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>